# Generated by Django 3.0.5 on 2022-05-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIPaginate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=100)),
                ('continuation', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Paginate',
            },
        ),
        migrations.CreateModel(
            name='AssetsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image_url', models.CharField(max_length=100)),
                ('chat_url', models.CharField(blank=True, max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('default_to_fiat', models.BooleanField()),
                ('description', models.TextField(blank=True, default='')),
                ('dev_buyer_fee_basis_points', models.CharField(blank=True, max_length=100)),
                ('dev_seller_fee_basis_points', models.CharField(blank=True, max_length=100)),
                ('discord_url', models.CharField(blank=True, max_length=100)),
                ('card_display_style', models.CharField(blank=True, max_length=100)),
                ('external_url', models.CharField(blank=True, max_length=100)),
                ('featured', models.BooleanField()),
                ('featured_image_url', models.CharField(blank=True, max_length=100)),
                ('hidden', models.BooleanField()),
                ('safelist_request_status', models.CharField(blank=True, max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=100)),
                ('is_subject_to_whitelist', models.CharField(blank=True, max_length=100)),
                ('large_image_url', models.CharField(blank=True, max_length=100)),
                ('medium_username', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('only_proxied_transfers', models.BooleanField()),
                ('opensea_buyer_fee_basis_points', models.CharField(blank=True, max_length=100)),
                ('opensea_seller_fee_basis_points', models.CharField(blank=True, max_length=100)),
                ('payout_address', models.CharField(blank=True, max_length=100)),
                ('require_email', models.BooleanField()),
                ('short_description', models.TextField(blank=True, default='')),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('telegram_url', models.CharField(blank=True, max_length=100)),
                ('twitter_username', models.CharField(blank=True, max_length=100)),
                ('instagram_username', models.CharField(blank=True, max_length=100)),
                ('wiki_url', models.CharField(blank=True, max_length=100)),
                ('is_nsfw', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Assets Collection',
            },
        ),
        migrations.CreateModel(
            name='AssetsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('representation', models.CharField(max_length=100)),
                ('mimeType', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('width', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Assets Image',
            },
        ),
        migrations.CreateModel(
            name='AssetsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('profile_img_url', models.CharField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('value', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Assets User',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('blockchain', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('tokenId', models.CharField(max_length=100)),
                ('mintedAt', models.CharField(max_length=100)),
                ('lastUpdatedAt', models.CharField(max_length=100)),
                ('supply', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('permalink', models.CharField(blank=True, max_length=100)),
                ('restriction', models.CharField(blank=True, max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('auction', models.CharField(blank=True, max_length=100)),
                ('totalStock', models.CharField(blank=True, max_length=100)),
                ('sellers', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('collection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='WebAPI.AssetsCollection')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='WebAPI.AssetsUsers')),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='WebAPI.AssetsImage')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='WebAPI.AssetsUsers')),
            ],
            options={
                'verbose_name': 'Asset',
            },
        ),
    ]
