# Generated by Django 3.0.5 on 2022-05-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_collection',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='asset_collection', to='WebAPI.AssetsCollection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='collection',
            field=models.CharField(max_length=100),
        ),
    ]
