# Generated by Django 3.0 on 2022-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitialassets',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
