# Generated by Django 3.0.5 on 2022-06-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIPaginate',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='best_order',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='collection_image',
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='AssetsCollection',
        ),
        migrations.DeleteModel(
            name='AssetsImage',
        ),
        migrations.DeleteModel(
            name='AssetsUsers',
        ),
        migrations.DeleteModel(
            name='BestOrders',
        ),
    ]
