# Generated by Django 3.0.5 on 2022-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0002_auto_20220623_0740'),
        ('WebAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='influencers',
            field=models.ManyToManyField(blank=True, to='TwitterApp.NftInfluencers'),
        ),
    ]
