# Generated by Django 3.0.5 on 2022-05-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0002_auto_20220520_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetsimage',
            old_name='url',
            new_name='aws_bucket_image_url',
        ),
        migrations.AddField(
            model_name='assetsimage',
            name='external_image_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
