# Generated by Django 3.0 on 2022-04-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0002_auto_20220429_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitialassets',
            old_name='blochain',
            new_name='blockchain',
        ),
    ]
