# Generated by Django 3.0 on 2022-05-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0002_auto_20220514_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUsers',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('followers_count', models.IntegerField(blank=True, default=0)),
                ('following_count', models.IntegerField(blank=True, default=0)),
                ('tweet_count', models.IntegerField(blank=True, default=0)),
                ('listed_count', models.IntegerField(blank=True, default=0)),
                ('verified', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=100)),
                ('created_at', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Twitter User',
            },
        ),
    ]
