# Generated by Django 3.0.5 on 2022-05-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0002_auto_20220520_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='image',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='owner',
        ),
        migrations.AddField(
            model_name='assets',
            name='creator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to='WebAPI.AssetsUsers'),
        ),
        migrations.AddField(
            model_name='assets',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_id', to='WebAPI.AssetsImage'),
        ),
        migrations.AddField(
            model_name='assets',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='WebAPI.AssetsUsers'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='asset_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_collection', to='WebAPI.AssetsCollection'),
        ),
    ]
