# Generated by Django 3.0 on 2022-05-18 12:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0003_twitterusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwwetData',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=10)),
                ('retweet_count', models.IntegerField(blank=True, default=0)),
                ('reply_count', models.IntegerField(blank=True, default=0)),
                ('like_count', models.IntegerField(blank=True, default=0)),
                ('quote_count', models.IntegerField(blank=True, default=0)),
                ('text', models.TextField()),
                ('in_reply_to_user_id', models.CharField(max_length=100)),
                ('referenced_tweets', jsonfield.fields.JSONField(default=dict)),
                ('mentions', jsonfield.fields.JSONField(default=dict)),
                ('author_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='WebAPI.TwitterUsers')),
            ],
            options={
                'verbose_name': 'Tweet Data',
            },
        ),
    ]
