# Generated by Django 3.0 on 2022-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0003_auto_20220429_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitialassets',
            name='image',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='photomedia',
            name='imageurl',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
