# Generated by Django 3.0.5 on 2022-05-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0003_auto_20220520_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255)),
                ('makeprice', models.CharField(blank=True, max_length=255)),
                ('takeprice', models.CharField(blank=True, max_length=255)),
                ('maker', models.CharField(blank=True, max_length=255)),
                ('taker', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Best Orders',
            },
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='card_display_style',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='chat_url',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='default_to_fiat',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='dev_buyer_fee_basis_points',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='dev_seller_fee_basis_points',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='featured_image_url',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='is_nsfw',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='is_subject_to_whitelist',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='large_image_url',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='medium_username',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='only_proxied_transfers',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='opensea_buyer_fee_basis_points',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='opensea_seller_fee_basis_points',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='payout_address',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='require_email',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='safelist_request_status',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='assetscollection',
            name='wiki_url',
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='blockchain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='buyer_fee_basis_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='collection_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='collection_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_image', to='WebAPI.AssetsImage'),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='colletion_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='external_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='fee_recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='minters',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='seller_fee_basis_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='symbol',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apipaginate',
            name='continuation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='apipaginate',
            name='total',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='auction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='blockchain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='collection',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='contract',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assets',
            name='lastUpdatedAt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='mintedAt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='permalink',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='platform',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='restriction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='supply',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='tokenId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='totalStock',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetscollection',
            name='discord_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetscollection',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetscollection',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsimage',
            name='aws_bucket_image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsimage',
            name='external_image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsimage',
            name='height',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsimage',
            name='mimeType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsimage',
            name='representation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsimage',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsimage',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetsimage',
            name='width',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetscollection',
            name='best_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_order', to='WebAPI.BestOrders'),
        ),
    ]
