# Generated by Django 3.0 on 2022-04-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0004_auto_20220429_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitialassets',
            name='category',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='WebAPI.Categories'),
        ),
    ]
