# Generated by Django 3.0 on 2022-05-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAPI', '0004_twwetdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twwetdata',
            name='author_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
