# Generated by Django 3.0.5 on 2022-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(blank=True, max_length=255)),
                ('collection_url', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('collection_type', models.CharField(blank=True, max_length=255)),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('collection_description', models.TextField(blank=True, default='')),
                ('trades', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255)),
                ('floor', models.CharField(blank=True, max_length=255)),
                ('collection_symbol', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('external_image_url', models.CharField(blank=True, max_length=255)),
                ('aws_bucket_image_url', models.CharField(blank=True, max_length=255)),
                ('external_link', models.CharField(blank=True, max_length=255)),
                ('buyer_fee_basis_points', models.CharField(blank=True, max_length=255)),
                ('seller_fee_basis_points', models.CharField(blank=True, max_length=255)),
                ('twitter_username', models.CharField(blank=True, max_length=255)),
                ('discord_url', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'NFT Collection',
            },
        ),
    ]
