# Generated by Django 3.0.5 on 2022-06-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTCollectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='collection_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
