# Generated by Django 3.0.5 on 2022-06-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFTCollectionApp', '0002_nftcollection_collection_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftcollection',
            old_name='colletion_description',
            new_name='collection_description',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='colletion_name',
            new_name='collection_name',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='colletion_symbol',
            new_name='collection_symbol',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='colletion_type',
            new_name='collection_type',
        ),
    ]
