# Generated by Django 3.0.5 on 2022-06-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFTCollectionApp', '0003_nftcollection_supply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftcollection',
            old_name='aws_bucket_image_url',
            new_name='averagePrice',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='buyer_fee_basis_points',
            new_name='awsBucketImageUrl',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='collection_id',
            new_name='collectionAddress',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='collection_description',
            new_name='collectionDescription',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='collection_name',
            new_name='collectionName',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='collection_symbol',
            new_name='collectionSymbol',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='collection_type',
            new_name='collectionType',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='collection_url',
            new_name='collectionUrl',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='created_at',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='discord_url',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='external_image_url',
            new_name='discordUrl',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='external_link',
            new_name='externalImageUrl',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='floor',
            new_name='externalLink',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='seller_fee_basis_points',
            new_name='floorPrice',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='supply',
            new_name='marketCap',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='trades',
            new_name='numOwners',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='twitter_username',
            new_name='numReports',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='updated_at',
            new_name='oneDayAveragePrice',
        ),
        migrations.RenameField(
            model_name='nftcollection',
            old_name='volume',
            new_name='oneDayChange',
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='oneDaySales',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='oneDayVolume',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='safelistRequestStatus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='sevenDayAveragePrice',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='sevenDayChange',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='sevenDaySales',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='sevenDayVolume',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='thirtyDayAveragePrice',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='thirtyDayChange',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='thirtyDaySales',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='thirtyDayVolume',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='totalSales',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='totalSupply',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='totalVolume',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='twitterUsername',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='updatedAt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
