# Generated by Django 3.0.5 on 2022-06-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFTCollectionApp', '0004_auto_20220616_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftcollection',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='nftcollection',
            name='updatedAt',
        ),
    ]
