# Generated by Django 3.0.5 on 2022-06-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdata',
            name='mentions',
        ),
        migrations.RemoveField(
            model_name='tweetdata',
            name='referenced_tweets',
        ),
    ]
