# Generated by Django 3.0.5 on 2022-06-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionSeedStatus',
        ),
    ]
