# Generated by Django 3.0.5 on 2022-06-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0002_delete_collectionseedstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSeedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Collection Seed Status',
            },
        ),
    ]
