# Generated by Django 3.0.5 on 2022-06-10 10:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0002_auto_20220610_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdata',
            name='mentions',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tweetdata',
            name='referenced_tweets',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
