# Generated by Django 3.0.5 on 2022-06-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0003_auto_20220610_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NftInfluencers',
        ),
    ]
