# Generated by Django 3.0.5 on 2022-06-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0003_collectionseedstatus'),
        ('TwitterApp', '0002_auto_20220620_1023'),
    ]

    operations = [
    ]
