# Generated by Django 3.0.5 on 2022-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0004_delete_nftinfluencers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftInfluencers',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Nft Influencers',
            },
        ),
    ]
