# Generated by Django 3.0.5 on 2022-06-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0005_nftinfluencers'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftinfluencers',
            name='created_at',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nftinfluencers',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
