# Generated by Django 3.0.5 on 2022-06-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwitterApp', '0006_auto_20220610_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSeedStatus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('collection_id', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Nft Influencers',
            },
        ),
        migrations.AddField(
            model_name='tweetdata',
            name='collection_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
